                                                                          # ML Lab AAssignment-3
                                                                          #  Name-> Vishal Dixit
                                                                          #  Section-> B(68)
                                                                          # University Roll No.-> 201500792
      
                                                                          # Submitted to:- Dr. Gaurav Kumar Sir




# -*- coding: utf-8 -*-
"""Matplotlib_Lab4_Assignment_3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qnN2oi3aNhxOOvgfs7D0GeXPgoB__ECc
"""

# Matplotlib Pyplot

import matplotlib.pyplot as plt
import numpy as np
xpoints=np.array([0,6])
ypoints=np.array([0,250])
plt.plot(xpoints, ypoints)
plt.show()

# Matplotlib Pyplot

import matplotlib.pyplot as plt
import numpy as np
# xpoints=np.array([0,6])
xpoints=np.array([0,1,2,3,4])
plt.plot(xpoints)
plt.show()

# Matplotlib Pyplot
# pLOTTING x and y points

import matplotlib.pyplot as plt
import numpy as np
xpoints=np.array([1,8])
ypoints=np.array([3,10])
plt.plot(xpoints, ypoints)
plt.show()

# Matplotlib Pyplot
# PLOTTING WITHOUT LINE

import matplotlib.pyplot as plt
import numpy as np
xpoints=np.array([1,8])
ypoints=np.array([3,10])
plt.plot(xpoints, ypoints, 'o')
plt.show()

# Matplotlib Pyplot

import matplotlib.pyplot as plt
import numpy as np
xpoints=np.array([1,2,6,8])
ypoints=np.array([3,8,1,10])
plt.plot(xpoints, ypoints)   # default x-points y-points
plt.show()

# Matplotlib Pyplot

import matplotlib.pyplot as plt
import numpy as np
xpoints=np.array([1,2,6,8,10,7,3])
# ypoints=np.array([3,8,1,10])
plt.plot(xpoints)  # default x-points
plt.show()

# Matplotlib Pyplot

import matplotlib.pyplot as plt
import numpy as np
ypoints=np.array([3,8,1,10,5,7])
plt.plot(ypoints,marker='o')        # default y-points
plt.show()

# Matplotlib Pyplot

import matplotlib.pyplot as plt
import numpy as np
ypoints=np.array([3,8,1,10,5,7])
plt.plot(ypoints,marker='*')   # marker as *
plt.show()

# Matplotlib Labels and Title

import matplotlib.pyplot as plt
import numpy as np
x=np.array([80,85,90,95,100,105,110,115,120,125])
y=np.array([240,250,260,270,280,290,300,310,320,330])
plt.plot(x,y)
plt.xlabel("Average Pulse")
plt.ylabel("Calorie Burnage")
plt.show()

# plot 1

import matplotlib.pyplot as plt
import numpy as np
x=np.array([80,85,90,95,100,105,110,115,120,125])
y=np.array([240,250,260,270,280,290,300,310,320,330])
plt.subplot(1,2,1)
plt.plot(x,y)
# plt.show()

#plot 2

import matplotlib.pyplot as plt
import numpy as np
x=np.array([1,2,6,8])
y=np.array([3,8,1,10])
plt.subplot(1,2,1)
plt.plot(x,y)
plt.show()

# Matplotlib Subplots

# plot 1

import matplotlib.pyplot as plt
import numpy as np
x=np.array([0,1,2,3])
y=np.array([3,8,1,10])
plt.subplot(2,1,1)
plt.plot(x,y)
# plt.show()

#plot 2

import matplotlib.pyplot as plt
import numpy as np
x=np.array([0,1,2,3])
y=np.array([10,20,30,40])
plt.subplot(2,1,2)
plt.plot(x,y)
plt.show()

# Matplotlib Subplots

# plot 1

import matplotlib.pyplot as plt
import numpy as np
x=np.array([0,1,2,3])
y=np.array([3,8,1,10])
plt.subplot(2,3,1)
plt.plot(x,y)
# plt.show()

#plot 2

import matplotlib.pyplot as plt
import numpy as np
x=np.array([0,1,2,3])
y=np.array([10,20,30,40])
plt.subplot(2,3,2)
plt.plot(x,y)
# plt.show()

# plot 3

import matplotlib.pyplot as plt
import numpy as np
x=np.array([0,1,2,3])
y=np.array([3,8,1,10])
plt.subplot(2,3,3)
plt.plot(x,y)
# plt.show()

#plot 4

import matplotlib.pyplot as plt
import numpy as np
x=np.array([0,1,2,3])
y=np.array([10,20,30,40])
plt.subplot(2,3,4)
plt.plot(x,y)
# plt.show()

# plot 5

import matplotlib.pyplot as plt
import numpy as np
x=np.array([0,1,2,3])
y=np.array([3,8,1,10])
plt.subplot(2,3,5)
plt.plot(x,y)
# plt.show()

#plot 6

import matplotlib.pyplot as plt
import numpy as np
x=np.array([0,1,2,3])
y=np.array([10,20,30,40])
plt.subplot(2,3,6)
plt.plot(x,y)
plt.show()

# matplotlib scatter

import matplotlib.pyplot as plt
import numpy as np
x=np.array([80,85,90,95,100,105,110,115,120,125])
y=np.array([240,250,260,270,280,290,300,310,320,330])
plt.scatter(x,y)
plt.show()

# matplotlib scatter

import matplotlib.pyplot as plt
import numpy as np
x=np.array([5,7,8,7,2,17,2,9,4,11,12,9,6])
y=np.array([99,86,87,88,111,86,103,87,94,78,77,85,86])
plt.scatter(x,y)
plt.show()

# Matplotlib Bars

import matplotlib.pyplot as plt
import numpy as np
x=np.array(["A","B","C","D"])
y=np.array([3,8,1,10])
plt.bar(x,y)
plt.show()

# Matplotlib Bar Color

import matplotlib.pyplot as plt
import numpy as np
x=np.array(["A","B","C","D"])
y=np.array([3,8,1,10])
plt.bar(x,y,color="RED")
plt.show()
plt.bar(x,y,width=0.1)

# Matplotlib Bar Color

import matplotlib.pyplot as plt
import numpy as np
x=np.array(["A","B","C","D"])
y=np.array([3,8,1,10])
plt.bar(x,y,color="RED")
plt.show()
plt.bar(x,y,width=0.8)

# Create Histogram

import matplotlib.pyplot as plt
import numpy as np
x = np.random.normal(170, 10, 250)
plt.hist(x)
plt.show()

# Matlplotlib Pie Chart

import matplotlib.pyplot as plt
import numpy as np
y = np.array([35, 25, 25, 15])
mylabels=["Apples", "Bananas", "Cherries", "Dates"]
plt.pie(y, labels=mylabels)
plt.show()

# Matplotlib Scatter (Compare Plots)

import matplotlib.pyplot as plt
import numpy as np

#DAY ONE, THE AGE AND SPEED OF 13 CARS:

x=np.array([5,7,8,7,2,17,2,9,4,11,12,9,6])
y=np.array([99,86,87,88,111,86,103,87,94,78,77,85,86])
plt.scatter(x,y)

#DAY TWO, THE AGE AND SPEED OF 15 CARS:

import matplotlib.pyplot as plt
import numpy as np
x=np.array([2,2,8,1,15,8,12,9,7,3,11,4,7,14,12])
y=np.array([100,105,84,105,90,99,90,95,94,100,79,112,91,80,85])
plt.scatter(x,y)
plt.show()

# Matplotlib Super Title

# plot 1

import matplotlib.pyplot as plt
import numpy as np
x=np.array([0,1,2,3])
y=np.array([3,8,1,10])
plt.subplot(1,2,1)
plt.plot(x,y)
plt.title("SALES")
# plt.show()

#plot 2

import matplotlib.pyplot as plt
import numpy as np
x=np.array([0,1,2,3])
y=np.array([10,20,30,40])
plt.subplot(1,2,2)
plt.plot(x,y)
plt.title("INCOME")
plt.suptitle("MY SHOP")
plt.show()