                                                                          # ML Lab AAssignment-2
                                                                          #  Name-> Vishal Dixit
                                                                          #  Section-> B(68)
                                                                          # University Roll No.-> 201500792
      
                                                                          # Submitted to:- Dr. Gaurav Kumar Sir
                                                                          

"""Lab3_pandas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gTc61QcNI0l19JqYVyYBzWfu0a8WOQuq
"""

#print all the data with rows and columns

import pandas as pd
df=pd.read_csv('/content/drive/MyDrive/data.csv')
print(df)

#print all the data 

import pandas as pd
df=pd.read_csv('/content/drive/MyDrive/data.csv');
print(df.to_string())

# Replace Only for Specified Columns.

import pandas as pd
df=pd.read_csv('/content/drive/MyDrive/data.csv')
df.fillna(130, inplace=True)
print(df.to_string())

# the average value of calories

import pandas as pd
df=pd.read_csv('/content/drive/MyDrive/data.csv')
x=df["Calories"].mean()
df["Calories"].fillna(x, inplace=True)    

print(df["Calories"].mean())

# Read data

import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/data.csv')		#how to read data
print(df.head(10))			#print first 10 rows of data
print(df.tail())				#print last 5 rows
print(df.head())				#print first 5 rows
print(df.info())				#it gives information about dataset

# the value in the middle 

import pandas as pd
df=pd.read_csv('/content/drive/MyDrive/data.csv')
x=df["Calories"].median()
df["Calories"].fillna(x, inplace=True)

print(df["Calories"].median())

# the valure that appears most frequently 

import pandas as pd
df=pd.read_csv('/content/drive/MyDrive/data.csv')
x=df["Calories"].mode()
df["Calories"].fillna(x, inplace=True)

print(df["Calories"].mode())

# Removing Duplicates

import pandas as pd
df=pd.read_csv('/content/drive/MyDrive/data.csv')
data=pd.DataFrame({'k1':["one","two"]*3+["two"],"k2":[1,1,2,3,3,4,4]})
print(data)

# Cleaning Wrong Date Format

import pandas as pd
df=pd.read_csv('/content/drive/MyDrive/data.csv')
df['Duration']=pd.to_datetime(df['Duration'])     #method for improve date format
print(df.to_string)

# gives the information about the data

import pandas as pd
df=pd.read_csv('/content/drive/MyDrive/data.csv')
df.info()

#print the pulse value greater than 100

import pandas as pd
df=pd.read_csv('/content/drive/MyDrive/data.csv')
for x in df.index:
  if df.loc[x,"Pulse"]>100:          # loc is used for labeled data
    print(df.loc[x,'Pulse'])

#for print the head value at 4

import pandas as pd 
df=pd.read_csv('/content/drive/MyDrive/data.csv')
print(df.head(4))

# for print bottom value at consider value 8

import pandas as pd 
df=pd.read_csv('/content/drive/MyDrive/data.csv')
print(df.tail(8))

# Delete Row when condition occurs:

import pandas as pd 
df=pd.read_csv('/content/drive/MyDrive/data.csv')
for x in df.index:
  if df.loc[x, "Duration"] > 120:
    df.drop(x, inplace = True)
    print(df["Duration"])